### ISSUE TITLE
Uglify error on running npm build

### ISSUE THREAD

**Issue by amusso01** [JPOak/strapped-wordpress-starter#1]
The error only occurs when running npm build, everything works fine on npm start and dev.
It should be something related with uglify, this is the error:

ERROR in main.js from UglifyJs
Unexpected token: punc «(»

I've tried to update uglify to the latest version 2.2.0, but without any success.
Also try to recompile all the ES6 code from my javascript to ES5 however, I believe some modules I import are written with ES6 syntax
Any idea - suggestion.
Thanks

**Comment by JPOak** [comment]
Hi. Per this thread I think I need to change over to the terser-webpack-plugin. See thread here for background: https://github.com/webpack/webpack/issues/5858

I actually already did this for my FoundationPress conversion see this file here: https://github.com/JPOak/FP-Webpack/blob/master/src/build/prod.config.js 

And add it to your package.json as well. The build process is basically the same for both. I'll probably make a push of the change over the next day or two.

**Comment by amusso01** [comment]
Just switch to terser-webpack-plugin as you suggested and now the building process is working perfectly.
